language: ruby
dist: trusty
sudo: false
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rake
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - ruby-head
  - jruby-9.1.12.0
  - jruby-head
